name: Create JSON File for Airports Subfolders

on:
  workflow_dispatch:

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate JSON file for Airports subfolders
        run: |
          #!/bin/bash
          OUTPUT_FILE="file_structure.json"
          ROOT_FOLDER="Airports"

          # Start the JSON structure
          echo "{" > $OUTPUT_FILE

          # Check if the root folder exists
          if [ -d "$ROOT_FOLDER" ]; then
            # Iterate through subfolders in Airports/
            for subfolder in "$ROOT_FOLDER"/*/; do
              SUBFOLDER_NAME=$(basename "$subfolder")

              # Find .ini and .py files in the subfolder
              FILES=$(find "$subfolder" -maxdepth 1 \( -name "*.ini" -o -name "*.py" \) -printf "\"%f\",\n" | sed '$s/,$//')

              if [ -n "$FILES" ]; then
                # Add to JSON structure
                echo "  \"$SUBFOLDER_NAME\": [" >> $OUTPUT_FILE
                echo "$FILES" | sed 's/^/    /' >> $OUTPUT_FILE
                echo "  ]," >> $OUTPUT_FILE
              fi
            done
          fi

          # Clean up trailing comma and close JSON structure
          sed -i '$s/,$//' $OUTPUT_FILE
          echo "}" >> $OUTPUT_FILE

      - name: Create new branch and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          # Create a new branch
          BRANCH_NAME="update-file-structure-$(date +%s)"
          git checkout -b $BRANCH_NAME

          # Add and commit the changes
          git add file_structure.json
          git commit -m "Auto-generate JSON file with Airports subfolder structure"

          # Push the new branch
          git push origin $BRANCH_NAME

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generate JSON file with Airports subfolder structure"
          branch: $BRANCH_NAME
          title: "Auto-generate JSON file"
          body: "This PR contains an updated file_structure.json generated by the workflow."
