name: Create JSON File for Airports Subfolders

on:
  workflow_dispatch: # Manual trigger

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate JSON file for Airports subfolders
        run: |
          #!/bin/bash
          OUTPUT_FILE="file_structure.json"
          ROOT_FOLDER="Airports"

          # Start the JSON structure
          echo "{" > $OUTPUT_FILE

          # Check if the root folder exists
          if [ -d "$ROOT_FOLDER" ]; then
            # Iterate through subfolders in Airports/
            for subfolder in "$ROOT_FOLDER"/*/; do
              SUBFOLDER_NAME=$(basename "$subfolder")

              # Find .ini and .py files in the subfolder
              FILES=$(find "$subfolder" -maxdepth 1 \( -name "*.ini" -o -name "*.py" \) -printf "\"%f\",\n" | sed '$s/,$//')

              if [ -n "$FILES" ]; then
                # Add to JSON structure
                echo "  \"$SUBFOLDER_NAME\": [" >> $OUTPUT_FILE
                echo "$FILES" | sed 's/^/    /' >> $OUTPUT_FILE
                echo "  ]," >> $OUTPUT_FILE
              fi
            done
          fi

          # Clean up trailing comma and close JSON structure
          sed -i '$s/,$//' $OUTPUT_FILE
          echo "}" >> $OUTPUT_FILE

      - name: Commit and push JSON file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

          git add file_structure.json
          git commit -m "Auto-generate JSON file with Airports subfolder structure"
          git push
