name: Test Pull Request Creation

on:
  workflow_dispatch:

jobs:
  test-create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create test branch
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git checkout -b test-pr-branch
          echo "Test PR content" > test-file.txt
          git add test-file.txt
          git commit -m "Add test file"
          git push origin test-pr-branch

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Add test file"
          branch: test-pr-branch # Head branch
          base: main             # Target branch
          title: "Test PR"
          body: "This is a test pull request."
